// Generated by CoffeeScript 1.7.1
"use strict";

/*
Module dependencies.
 */
var Schema, User, UserSchema, callback, crypto, db, mongoose;

mongoose = require("mongoose");

mongoose.connect("mongodb://localhost/venmo-example");

db = mongoose.connection;

db.on("error", console.error.bind(console, "connection error:"));

db.once("open", callback = function() {
  console.log("mongoose connection is open");
});

Schema = mongoose.Schema;

crypto = require("crypto");


/*
User Schema
 */

UserSchema = new Schema({
  name: {
    type: String,
    required: true
  },
  email: String,
  username: {
    type: String,
    unique: true
  },
  balance: String,
  provider: String,
  salt: String,
  venmo: {},
  access_token: String,
  refresh_token: String
});

User = mongoose.model("User", UserSchema);

module.exports = {
  User: User
};
